version: '3'

services:
  mlapi:
    build: .
    container_name: ml_api
    volumes:
      - .:/app
    ports:
      - "8000:5000"
    #to exec test model
    command: sh -c "python manage.py test mlmodel && python manage.py runserver 0.0.0.0:5000"
