# Generated by Django 5.0.2 on 2024-03-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pivot_Iris_setosa', models.FloatField()),
                ('pivot_Iris_versicolor', models.FloatField()),
                ('pivot_Iris_virginica', models.FloatField()),
            ],
        ),
    ]
