name: First WorkFlow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print greeting
      run: echo "hello world"
    - name: Prints goodbye
      run: echo "Done - Bye!"
    - name: Prints goodbye other agains
      run: echo "Done - Bye! agains"
